// Python levels for Worlds 4–5. Programs run on the Kaimana code runner
// (Python 3), and a level passes when the normalized stdout equals each
// test's `expected`. Every `solution` below is written so its output matches
// its tests exactly — keep them in sync when editing.

import type { PythonLevel } from "./types";

export const ISLAND_LEVELS: PythonLevel[] = [
  {
    kind: "python",
    id: "island-hello-world",
    slug: "hello-world",
    title: "Hello, World!",
    story: "Welcome to Python Island! Here you type real code, just like real programmers.",
    learn: ["`print()` makes Python show a message on the screen.", "Put your words inside quote marks, like `\"this\"`."],
    example: { code: 'print("Hi there!")', output: "Hi there!" },
    task: "Make Python print exactly: `Hello, world!`",
    starterCode: '# Type your message between the quote marks\nprint("")\n',
    tests: [{ expected: "Hello, world!" }],
    hints: ["Your message goes between the two quote marks inside `print(\"\")`.", "Check the capital H, the comma, and the ! at the end."],
    solution: 'print("Hello, world!")\n',
  },
  {
    kind: "python",
    id: "island-line-by-line",
    slug: "line-by-line",
    title: "Line by Line",
    story: "I wrote a poem! Can you help me show it off?",
    learn: ["Each `print()` shows one line.", "Python runs your code from top to bottom, one line at a time."],
    example: { code: 'print("Ready")\nprint("Set")\nprint("Go!")', output: "Ready\nSet\nGo!" },
    task: "Print Bolt's poem, using one `print()` for each line.",
    starterCode: 'print("Roses are red")\n',
    tests: [{ expected: "Roses are red\nRobots are blue\nI love to code\nAnd so can you!" }],
    hints: ["You need 4 `print()` lines, one for each line of the poem.", "The first line is done for you. Copy it onto a new line and change the words."],
    solution: 'print("Roses are red")\nprint("Robots are blue")\nprint("I love to code")\nprint("And so can you!")\n',
  },
  {
    kind: "python",
    id: "island-robot-maths",
    slug: "robot-maths",
    title: "Robot Maths",
    story: "Python is a super-fast calculator. Let's count my bolts!",
    learn: ["Numbers don't need quote marks.", "Use `+` to add, `-` to take away and `*` to multiply."],
    example: { code: "print(7 + 5)\nprint(10 - 3)\nprint(2 * 5)", output: "12\n7\n10" },
    task: "Bolt has 3 boxes with 8 bolts in each, plus 5 spare bolts. Print the total by putting the sum `3 * 8 + 5` inside `print()`.",
    starterCode: "# Let Python do the maths for you\nprint()\n",
    tests: [
      {
        expected: "29",
        mistakes: [
          {
            output: "3 * 8 + 5",
            tip: "Python printed your sum as words because of the quote marks. Take the quotes away so Python does the maths!",
          },
        ],
      },
    ],
    hints: ["Put the sum inside the brackets of `print()`, with no quote marks.", "`print(3 * 8 + 5)`"],
    solution: "print(3 * 8 + 5)\n",
  },
  {
    kind: "python",
    id: "island-words-and-numbers",
    slug: "words-and-numbers",
    title: "Words and Numbers",
    story: "Let's put words and numbers together in one line.",
    learn: ["Put commas between things inside `print()` to show them on one line.", "Python adds a space between each thing for you."],
    example: { code: 'print("I have", 2, "cats")', output: "I have 2 cats" },
    task: "Print `Bolt is 3 years old`, but let Python work out the 3 by writing `1 + 2`.",
    starterCode: 'print("Bolt is")\n',
    tests: [
      {
        expected: "Bolt is 3 years old",
        mistakes: [
          {
            output: "Bolt is 1 + 2 years old",
            tip: "The sum is inside quote marks, so Python printed it as words. Put `1 + 2` outside the quotes, between two commas.",
          },
        ],
      },
    ],
    hints: ["You need three things with commas between them: some words, a sum, and more words.", '`print("Bolt is", 1 + 2, "years old")`'],
    solution: 'print("Bolt is", 1 + 2, "years old")\n',
  },
  {
    kind: "python",
    id: "island-text-tricks",
    slug: "text-tricks",
    title: "Text Tricks",
    story: "Words can do tricks too! Let's make a cheer.",
    learn: ["`+` glues pieces of text together.", '`*` repeats text: `"ha" * 3` makes `hahaha`.'],
    example: { code: 'print("Bo" + "lt")\nprint("la" * 3)', output: "Bolt\nlalala" },
    task: 'Print `Hip Hip Hooray!` using `*` to repeat `"Hip "` two times, then `+` to add `"Hooray!"`.',
    starterCode: '# Repeat "Hip " two times, then add "Hooray!"\nprint()\n',
    tests: [
      {
        expected: "Hip Hip Hooray!",
        mistakes: [{ output: "HipHipHooray!", tip: 'Don\'t forget the space after Hip inside the quotes: `"Hip "`.' }],
      },
    ],
    hints: ['`"Hip " * 2` makes `Hip Hip ` (see the space after each Hip?).', '`print("Hip " * 2 + "Hooray!")`'],
    solution: 'print("Hip " * 2 + "Hooray!")\n',
  },
  {
    kind: "python",
    id: "island-brackets-first",
    slug: "brackets-first",
    title: "Brackets First!",
    story: "Python follows maths rules. Brackets can change the answer!",
    learn: ["Python does `*` before `+`, just like in maths class.", "Put brackets `( )` around the part you want Python to do first."],
    example: { code: "print(1 + 2 * 10)\nprint((1 + 2) * 10)", output: "21\n30" },
    task: "On the first line, print the answer to `(6 + 4) * 5`. On the second line, print `6 + 4 * 5`. Are they the same?",
    starterCode: "print()\nprint()\n",
    tests: [{ expected: "50\n26" }],
    hints: ["Put each sum inside its own `print()`. Keep the brackets in the first one!", "`print((6 + 4) * 5)` and then `print(6 + 4 * 5)`"],
    solution: "print((6 + 4) * 5)\nprint(6 + 4 * 5)\n",
  },
];

export const STATION_LEVELS: PythonLevel[] = [
  {
    kind: "python",
    id: "station-variable-boxes",
    slug: "variable-boxes",
    title: "Variable Boxes",
    story: "Welcome to Star Station! Up here, programs can remember things.",
    learn: ["A variable is like a box with a name. `=` puts a value into the box.", "Use the box's name (with no quote marks) to get the value back out."],
    example: { code: 'pet = "cat"\nlegs = 4\nprint(pet, "has", legs, "legs")', output: "cat has 4 legs" },
    task: "The boxes `robot` and `stars` are ready. Use them both to print `Bolt has 5 stars`.",
    starterCode: 'robot = "Bolt"\nstars = 5\n# Print a sentence using robot and stars\n',
    tests: [
      {
        expected: "Bolt has 5 stars",
        mistakes: [
          {
            output: "robot has stars stars",
            tip: "Python printed the names of the boxes because they were inside quote marks. Leave the quotes off `robot` and `stars`.",
          },
        ],
      },
    ],
    hints: ['Use commas: the `robot` box, the word `"has"`, the `stars` box, then the word `"stars"`.', '`print(robot, "has", stars, "stars")`'],
    solution: 'robot = "Bolt"\nstars = 5\nprint(robot, "has", stars, "stars")\n',
  },
  {
    kind: "python",
    id: "station-hello-you",
    slug: "hello-you",
    title: "Hello, You!",
    story: "I want to welcome every new astronaut by name.",
    learn: [
      "`input()` waits for someone to type an answer, then gives it to your program.",
      "Save the answer in a variable. Keep the brackets empty: our tester types the answer for you.",
    ],
    example: { code: 'food = input()\nprint("Yum, " + food + "!")', stdin: "pizza", output: "Yum, pizza!" },
    task: "Read a name with `input()`, then welcome that astronaut. If the tester types `Sam`, print `Welcome aboard, Sam!`",
    starterCode: "name = input()\n# Welcome the astronaut here\n",
    tests: [
      { stdin: "Sam\n", expected: "Welcome aboard, Sam!" },
      { stdin: "Maya\n", expected: "Welcome aboard, Maya!" },
    ],
    hints: ["Glue the words and the `name` box together with `+`, like in the example.", '`print("Welcome aboard, " + name + "!")`'],
    solution: 'name = input()\nprint("Welcome aboard, " + name + "!")\n',
  },
  {
    kind: "python",
    id: "station-adding-machine",
    slug: "adding-machine",
    title: "Adding Machine",
    story: "Uh-oh, my adding machine is broken! Can you fix it?",
    learn: ["`input()` always gives you text, even when someone types a number.", "Wrap it in `int()` to turn the text into a number you can do maths with."],
    example: { code: "age = int(input())\nprint(age + 1)", stdin: "9", output: "10" },
    task: "The tester types two numbers, each on its own line. Print their sum. Right now the machine prints `1230` instead of `42`. Fix it!",
    starterCode: "first = input()\nsecond = input()\nprint(first + second)\n",
    tests: [
      {
        stdin: "12\n30\n",
        expected: "42",
        mistakes: [{ output: "1230", tip: "The numbers got glued together like words! Use `int(input())` so Python treats them as numbers." }],
      },
      {
        stdin: "7\n8\n",
        expected: "15",
        mistakes: [{ output: "78", tip: "The numbers got glued together like words! Use `int(input())` so Python treats them as numbers." }],
      },
    ],
    hints: ['Right now `first` and `second` are text, and `"12" + "30"` glues them into `1230`.', "Change both input lines to `int(input())`."],
    solution: "first = int(input())\nsecond = int(input())\nprint(first + second)\n",
  },
  {
    kind: "python",
    id: "station-hot-or-cold",
    slug: "hot-or-cold",
    title: "Hot or Cold?",
    story: "I pick my treat depending on the weather. Help me decide!",
    learn: [
      "`if` lets your program choose. When the test is true, the pushed-in lines under it run.",
      "`else` runs when the test is false. End both lines with a colon `:` and push the next line in with 4 spaces.",
    ],
    example: { code: 'score = 7\nif score > 5:\n    print("You win!")\nelse:\n    print("Try again!")', output: "You win!" },
    task: "Read a temperature. If it is more than `25`, print `Ice cream time!` Otherwise, print `Hot chocolate time!`",
    starterCode: "temp = int(input())\n# Choose a treat with if and else\n",
    tests: [
      { stdin: "30\n", expected: "Ice cream time!" },
      { stdin: "12\n", expected: "Hot chocolate time!" },
    ],
    hints: [
      "Start with `if temp > 25:` and push the next line in with 4 spaces.",
      '`if temp > 25:` then `print("Ice cream time!")`, then `else:` then `print("Hot chocolate time!")`. Push both prints in with 4 spaces.',
    ],
    solution: 'temp = int(input())\nif temp > 25:\n    print("Ice cream time!")\nelse:\n    print("Hot chocolate time!")\n',
  },
  {
    kind: "python",
    id: "station-loop-the-loop",
    slug: "loop-the-loop",
    title: "Loop the Loop",
    story: "Loops let me repeat things without ever getting tired.",
    learn: ["`for` repeats the pushed-in lines once for every number in `range()`.", "`range(1, 4)` counts 1, 2, 3. It stops just before the last number!"],
    example: { code: 'for i in range(1, 4):\n    print("Jump", i)', output: "Jump 1\nJump 2\nJump 3" },
    task: "Print the 5 times table, from `5 x 1 = 5` up to `5 x 5 = 25`.",
    starterCode: "for i in range(1, 6):\n    print(i)\n",
    tests: [{ expected: "5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25" }],
    hints: ["Inside the loop, `i` is 1, then 2, then 3… and `5 * i` is the answer.", '`print("5 x", i, "=", 5 * i)`'],
    solution: 'for i in range(1, 6):\n    print("5 x", i, "=", 5 * i)\n',
  },
  {
    kind: "python",
    id: "station-rocket-countdown",
    slug: "rocket-countdown",
    title: "Rocket Countdown",
    story: "Final mission: launch my rocket!",
    learn: ["`range()` can count backwards! `range(3, 0, -1)` gives 3, 2, 1.", "The third number is the step. `-1` means go down by one each time."],
    example: { code: 'for n in range(3, 0, -1):\n    print(n)\nprint("Go!")', output: "3\n2\n1\nGo!" },
    task: "Read a number. Count down from that number to `1`, then print `Blast off!`",
    starterCode: 'start = int(input())\n# Count down from start to 1\n\nprint("Blast off!")\n',
    tests: [
      { stdin: "5\n", expected: "5\n4\n3\n2\n1\nBlast off!" },
      { stdin: "3\n", expected: "3\n2\n1\nBlast off!" },
    ],
    hints: ["Use a `for` loop with `range(start, 0, -1)`.", "`for n in range(start, 0, -1):` and then `print(n)` pushed in with 4 spaces."],
    solution: 'start = int(input())\nfor n in range(start, 0, -1):\n    print(n)\nprint("Blast off!")\n',
  },
];
