// Block-puzzle levels for Worlds 1–3. Every board's reference solution is
// checked by lib/kids/verifyCurriculum.local.mts: it must reach the flag,
// collect every gem, and use exactly `optimalBlocks` blocks.

import type { PuzzleLevel } from "./types";

export const MEADOW_LEVELS: PuzzleLevel[] = [
  {
    kind: "puzzle",
    id: "meadow-first-steps",
    slug: "first-steps",
    title: "First Steps",
    story: "Hi, I'm Bolt! Can you help me roll over to the flag?",
    goal: "Get Bolt to the flag.",
    board: ["#.#.#", "S...G", "..#.."],
    startDir: "E",
    palette: ["forward"],
    newBlocks: ["forward"],
    optimalBlocks: 4,
    solution: "F F F F",
    hints: ["Each Move forward block moves Bolt one square.", "Count the squares between Bolt and the flag. That's how many Move forward blocks you need!"],
  },
  {
    kind: "puzzle",
    id: "meadow-turn-the-corner",
    slug: "turn-the-corner",
    title: "Turn the Corner",
    story: "The path bends! I can turn left and right.",
    goal: "Turn the corner and reach the flag.",
    board: ["S..", "##.", "##G"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight"],
    newBlocks: ["turnLeft", "turnRight"],
    optimalBlocks: 5,
    solution: "F F R F F",
    hints: [
      "Turning doesn't move Bolt. It only changes the way Bolt is facing.",
      "Left and right are from Bolt's point of view. Look where Bolt's eyes point!",
      "Move forward 2 times, turn right, then move forward 2 more times.",
    ],
  },
  {
    kind: "puzzle",
    id: "meadow-left-and-right",
    slug: "left-and-right",
    title: "Left and Right",
    story: "This path turns one way and then the other.",
    goal: "Follow the path to the flag.",
    board: ["S..#", "##.#", "##.G"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight"],
    optimalBlocks: 7,
    solution: "F F R F F L F",
    hints: ["Trace the path with your finger first. Where does it turn?", "You need one right turn and one left turn."],
  },
  {
    kind: "puzzle",
    id: "meadow-about-face",
    slug: "about-face",
    title: "About Face",
    story: "Oops, I'm facing the wrong way! Can you turn me around?",
    goal: "Turn around and find the flag.",
    board: ["G.#", "#.#", "#S#"],
    startDir: "S",
    palette: ["forward", "turnLeft", "turnRight"],
    optimalBlocks: 6,
    solution: "L L F F L F",
    hints: ["Two turns the same way make Bolt face the other way.", "Turn around, move forward 2, then turn left and roll onto the flag."],
  },
  {
    kind: "puzzle",
    id: "meadow-maze",
    slug: "maze",
    title: "Meadow Maze",
    story: "A twisty maze! Plan the whole path before you press Run.",
    goal: "Find your way through the maze.",
    board: ["S.#G#", "#.#.#", "#...#"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight"],
    optimalBlocks: 10,
    solution: "F R F F L F F L F F",
    hints: ["Bolt goes down, across, then up.", "The turns are: right, then left, then left again."],
  },
];

export const LAGOON_LEVELS: PuzzleLevel[] = [
  {
    kind: "puzzle",
    id: "lagoon-long-bridge",
    slug: "long-bridge",
    title: "Long Bridge",
    story: "This bridge is looong! A Repeat block saves you lots of work.",
    goal: "Cross the bridge using a loop.",
    board: ["#######", "S.....G", "#######"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat"],
    newBlocks: ["repeat"],
    optimalBlocks: 2,
    solution: "6{F}",
    hints: [
      "A Repeat block runs the blocks inside it again and again.",
      "Add a Repeat block, tap its “Add blocks here” button, then add one Move forward inside it.",
      "Set the Repeat block to 6 times.",
    ],
  },
  {
    kind: "puzzle",
    id: "lagoon-island-loop",
    slug: "island-loop",
    title: "Island Loop",
    story: "Let's sail around the little island. Do you see a pattern?",
    goal: "Go around the island to the flag.",
    board: ["S..", "##.", "G.."],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat"],
    optimalBlocks: 4,
    solution: "3{F F R}",
    hints: ["Forward, forward, turn… forward, forward, turn… That's a pattern!", "Repeat 3 times: Move forward, Move forward, Turn right."],
  },
  {
    kind: "puzzle",
    id: "lagoon-stepping-stones",
    slug: "stepping-stones",
    title: "Stepping Stones",
    story: "Hop down the stepping stones, one step at a time.",
    goal: "Hop down the stones to the flag.",
    board: ["S.###", "#..##", "##..#", "###.G"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat"],
    optimalBlocks: 5,
    solution: "4{F R F L}",
    hints: ["Every step uses the same 4 moves. Find them for the first step.", "Repeat 4 times: forward, turn right, forward, turn left."],
  },
  {
    kind: "puzzle",
    id: "lagoon-up-and-over",
    slug: "up-and-over",
    title: "Up and Over",
    story: "Climb up the rocks, then climb back down the other side!",
    goal: "Climb over the rocks to the flag.",
    board: ["###..##", "##....#", "#..##..", "S.####G"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat"],
    optimalBlocks: 10,
    solution: "3{F L F R} 3{F R F L}",
    hints: [
      "Going up is one pattern and going down is another. You can use two Repeat blocks!",
      "Up: repeat 3 times forward, left, forward, right. Down: repeat 3 times forward, right, forward, left.",
    ],
  },
  {
    kind: "puzzle",
    id: "lagoon-loop-in-a-loop",
    slug: "loop-in-a-loop",
    title: "Loop in a Loop",
    story: "Here's a secret: you can put a loop inside another loop!",
    goal: "Sail around the lagoon with a loop inside a loop.",
    board: ["S....", "####.", "####.", "####.", "G...."],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat"],
    optimalBlocks: 4,
    solution: "3{4{F} R}",
    hints: [
      "Each side of the lagoon is 4 moves forward, then a turn.",
      "Inside: repeat 4 times Move forward, then Turn right. Outside: repeat all of that 3 times.",
    ],
  },
];

export const CAVES_LEVELS: PuzzleLevel[] = [
  {
    kind: "puzzle",
    id: "caves-gem-hunt",
    slug: "gem-hunt",
    title: "Gem Hunt",
    story: "Sparkly gems! I have to pick up every gem before I reach the flag.",
    goal: "Collect both gems, then reach the flag.",
    board: ["#######", "S.*.*.G", "#######"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat", "collect"],
    newBlocks: ["collect"],
    optimalBlocks: 4,
    solution: "3{F F P}",
    hints: ["Pick up gem only works when Bolt is standing on a gem.", "Repeat 3 times: Move forward, Move forward, Pick up gem."],
  },
  {
    kind: "puzzle",
    id: "caves-look-ahead",
    slug: "look-ahead",
    title: "Look Ahead",
    story: "This cave spirals round and round. Good thing I have a wall sensor!",
    goal: "Use the wall sensor to spiral into the flag.",
    board: ["S....", "####.", "..G#.", ".###.", "....."],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat", "repeatUntil", "ifWallAhead"],
    newBlocks: ["repeatUntil", "ifWallAhead"],
    optimalBlocks: 4,
    solution: "U{?wall{R}:{F}}",
    hints: [
      "Repeat until flag keeps going until Bolt is on the flag. No counting needed!",
      "Bolt should turn when there's a wall ahead, and move forward when there isn't.",
      "Repeat until flag: If wall ahead → Turn right, otherwise → Move forward.",
    ],
  },
  {
    kind: "puzzle",
    id: "caves-gem-detector",
    slug: "gem-detector",
    title: "Gem Detector",
    story: "These gems are all mixed up. Let's check every square for gems!",
    goal: "Collect every gem and reach the flag.",
    board: ["########", "S.**.*.G", "########"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat", "repeatUntil", "collect", "ifGemHere"],
    newBlocks: ["ifGemHere"],
    optimalBlocks: 4,
    solution: "U{?gem{P} F}",
    hints: [
      "The gems don't follow a pattern, so let Bolt check each square instead.",
      "Repeat until flag: If gem here → Pick up gem. Then Move forward (outside the If block).",
    ],
  },
  {
    kind: "puzzle",
    id: "caves-crystal-spiral",
    slug: "crystal-spiral",
    title: "Crystal Spiral",
    story: "Gems AND walls! Use both of my sensors to get through.",
    goal: "Spiral in, collect all 4 gems, and reach the flag.",
    board: [".*...", ".###.", "*.G#*", "####.", "S.*.."],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeat", "repeatUntil", "collect", "ifWallAhead", "ifGemHere"],
    optimalBlocks: 6,
    solution: "U{?gem{P} ?wall{L}:{F}}",
    hints: [
      "Inside the loop, first check for a gem, then check for a wall.",
      "This spiral turns left, not right.",
      "Repeat until flag: If gem here → Pick up gem. Then If wall ahead → Turn left, otherwise → Move forward.",
    ],
  },
  {
    kind: "puzzle",
    id: "caves-twisty-tunnel",
    slug: "twisty-tunnel",
    title: "Twisty Tunnel",
    story: "The last tunnel turns left AND right. I can peek to the sides!",
    goal: "Make Bolt choose the right turn every time.",
    board: ["#G...", "####.", "##...", "##.##", "S..##"],
    startDir: "E",
    palette: ["forward", "turnLeft", "turnRight", "repeatUntil", "ifWallAhead", "ifPathLeft", "ifPathRight"],
    newBlocks: ["ifPathLeft", "ifPathRight"],
    optimalBlocks: 6,
    solution: "U{?wall{?left{L}:{R}}:{F}}",
    hints: [
      "When there's a wall ahead, Bolt has to pick: left or right?",
      "You can put an If block inside another If block.",
      "Repeat until flag: If wall ahead → (If path to the left → Turn left, otherwise → Turn right), otherwise → Move forward.",
    ],
  },
];
