"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { appConfig } from "@/lib/config";
import { SiteHeader } from "../_components/home/SiteHeader";
import { SiteFooter } from "../_components/home/SiteFooter";
type User = { name: string; email: string; role: string; status: string; profilePicUrl?: string; createdAt: string };
export default function ProfilePage() {
  const [user, setUser] = useState<User | null>(null); const [state, setState] = useState("Loading your profile…");
  useEffect(() => { fetch(`${appConfig.apiUrl}/api/auth/me`, { credentials: "include" }).then(async r => { const b = await r.json(); if (!r.ok) throw new Error(b.message); setUser(b.data); }).catch(e => setState(e instanceof Error ? e.message : "Please sign in to view your profile.")); }, []);
  return <><SiteHeader /><main className="dashboard-shell"><div className="dashboard-head"><div><p className="eyebrow">YOUR ARENA / PROFILE</p><h1>Profile & progress</h1><p>Keep your identity, streak and learning goals in one place.</p></div><Link className="button button-small" href="/problems">Continue solving <span>→</span></Link></div>{user ? <><section className="profile-card profile-hero"><div className="avatar">{user.profilePicUrl ? <Image src={user.profilePicUrl} alt={`${user.name} profile`} width={112} height={112} priority /> : user.name.slice(0, 1).toUpperCase()}</div><div className="profile-identity"><span className="panel-kicker">CODER PROFILE</span><h2>{user.name}</h2><p>{user.email}</p><span className="status-pill">● {user.status} · {user.role}</span></div><div className="profile-actions"><Link className="button button-small" href="/submissions">View submissions</Link><Link className="text-link" href="/analytics">Open analytics →</Link></div></section><section className="metric-grid"><article><b>0</b><span>Problems solved</span><small>Start your first challenge</small></article><article><b>0 days</b><span>Current streak</span><small>Consistency compounds</small></article><article><b>{new Date(user.createdAt).toLocaleDateString()}</b><span>Member since</span><small>Welcome to Kaimana</small></article></section><section className="profile-columns"><article className="profile-panel"><span className="panel-kicker">NEXT MOVE</span><h2>Build your solving rhythm.</h2><p>Choose a problem, submit an approach and use every result as feedback.</p><Link className="text-link" href="/problems">Browse problem library →</Link></article><article className="profile-panel"><span className="panel-kicker">ACCOUNT</span><div className="detail-row"><span>Account status</span><strong>{user.status}</strong></div><div className="detail-row"><span>Access level</span><strong>{user.role}</strong></div><div className="detail-row"><span>Profile email</span><strong>{user.email}</strong></div></article></section></> : <div className="empty-panel">{state}<Link href="/signin">Sign in to continue →</Link></div>}</main><SiteFooter /></>;
}
